name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug Docker Login
      run: |
        echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
        echo "Logging into Docker Hub..."
        docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

            
    - name: Build the Docker image
      run: |
        docker build -t mernagamal/laravel-authentication:latest .
    
    - name: Push Docker image
      run: |
        docker push mernagamal/laravel-authentication:latest
